### ISSUE TITLE
Fehler im CSS

### ISSUE THREAD

**Issue by katgirl** [contao-themes-net/zero-one-theme-bundle#11]
```css
.navbar .navbar-section {
    a2lign-items: center;
    d2isplay: flex;
    f2lex: 1 0 0;
}
```
müsste 
```css
.navbar .navbar-section {
    align-items: center;
    display: flex;
    flex: 1 0 0;
}
```
lauten, dann allerdings darf das flex so nicht definiert sein, da das Menü sonst nicht passt.
