### ISSUE TITLE
Activate Strict Mode (MySQL) with Host IONOS / CONTAO Database Server Problem

### ISSUE THREAD

**Issue by keeperschmiede** [contao-themes-net/zero-one-theme-bundle#19]
Hi together, when I start my CONTAO Install Manager, I always get the following error code:

"Your database server is not running in the strict mode! Please activate the Strict Mode in your my.cnf data or configurate the connection oprions in the data config/config.yml as follows:

doctrine:
  dbal:
    connections:
      default:
        options:
          1002: "SET SESSION sql_mode=(SELECT CONCAT(@@sql_mode, ',TRADITIONAL'))"

Always I try to import a contao theme in the contao manager it fails, because of this problem, the server sais: 

"The import could not be completed!
SQLSTATE[23000]: Integrity constraint violation: 1062 duplicate entry "115" for key "PRIMARY".

I cannot find the part where I can configurate the MySQL and I also do not know, how to put in the code and what to do. Can anybody help me? Thank you very much!

**Comment by MDevster** [comment]
Hi @keeperschmiede,

this has nothing to do with the theme but with Contao itself. you can simply add the lines described above under config/config.yml or if the file does not exist you can create it:

# Pfad
`ROOT/config/config.yml`

# Inhalt
```
doctrine:
   dbal:
       connections:
           default:
               options:
                   # Depending on the DB driver, the option key is either 1002 (pdo_mysql) or 3 (mysqli)
                   1002: "SET SESSION sql_mode=(SELECT CONCAT(@@sql_mode, ',TRADITIONAL'))"
```

See also:
https://github.com/contao/managed-edition#mysql-strict-mode
oder
https://community.contao.org/de/showthread.php?81500-Problem-bei-Update-von-4-11-zu-4-12-(Strict-Mode)&goto=newpost

If your config.yml is still under app/config/config.yml you can add the lines there or move the file to config/, because this is the new/recommended "place", see 
https://docs.contao.org/manual/de/system/einstellungen/#zus%C3%A4tzliche-backend-einstellungen
